### ISSUE TITLE
`Light` view mode cursor not visible in command input window

### ISSUE THREAD

**Issue by SergeyMi37** [SeanConnelly/DevBox#10]
![image](https://github.com/SeanConnelly/DevBox/assets/18187317/986dd501-b612-42c9-aa44-13e35e0ab5cb)
`Light` view mode cursor not visible in command input window

**Comment by SeanConnelly** [comment]
Fixed

**Comment by SergeyMi37** [comment]
Thank you. That's enough for easy work.
I look forward to the birth of the beta version
