### ISSUE TITLE
How to be? I'm not sure if I reverted the changes correctly and I want to close the tab without saving.

### ISSUE THREAD

**Issue by SergeyMi37** [SeanConnelly/DevBox#3]
![image](https://github.com/SeanConnelly/DevBox/assets/18187317/dadf5477-a624-4b0a-af27-e223d660e670)

I suggest to allow closing after warning.

**Comment by SeanConnelly** [comment]
The "has changed" state is not very sophisticated. It should be able to handle reverting as well. I will put this on my task list to do.

In the mean time, you can use the View > Reset option in the main menu to reset and force everthing to close.

**Comment by SergeyMi37** [comment]
Thx

**Comment by SergeyMi37** [comment]
Thx
