### ISSUE TITLE
Is it possible to execute the object script command without a web terminal in the devbox panel?

### ISSUE THREAD

**Issue by SergeyMi37** [SeanConnelly/DevBox#4]

**Comment by SeanConnelly** [comment]
There is a code assistant window. If you click on the box icon in the top right then it will open up. It might need a couple of click (small issue to fix). You can type into the code assistant but at the moment it only responds to

write
do
select

where select will run a query

the write will intercept the value and try and dump objects out verbosely.

anything else and it will try and process the text as a GPT question, which will require a token.

The code runner is very basic at the moment, dont be suprised if it errors here and there, I plan on making this more robust and more feature packed down the line.

**Comment by SergeyMi37** [comment]
I don't need an assistant. I would like to run the code like in CStudio in the output panel.

**Comment by SeanConnelly** [comment]
OK, sure, I can wire that up as well, but I have no plans to make it session based at the moment, it will just be fire a forget. 

One thing I did considering was embedding Web Terminal into that bottom panel as an iframe if it detects its installed.

**Comment by SergeyMi37** [comment]
yes, that's also possible
