### ISSUE TITLE
Web terminal loading error

### ISSUE THREAD

**Issue by SergeyMi37** [SeanConnelly/DevBox#5]
![image](https://github.com/SeanConnelly/DevBox/assets/18187317/d04f3170-76d3-4730-b6ca-424ed9a80be1)

**Comment by SergeyMi37** [comment]
the problem is solved if you change
```
 if (utilName === 'Web Terminal') window.open(`/terminal/?NS=${ns}`);
```

**Comment by SeanConnelly** [comment]
Fixed :) Thx
