### ISSUE TITLE
Error executing commands in namespace %SYS

### ISSUE THREAD

**Issue by SergeyMi37** [SeanConnelly/DevBox#7]
You can execute commands! It's just great! But there are mistakes

![image](https://github.com/SeanConnelly/DevBox/assets/18187317/76bff055-43ce-4447-9796-7af4a90607d8)

And in the other `USER` it works 
It's in docker.

**Comment by SergeyMi37** [comment]
If installed natively, then the error in the system `%SYS` remains.

And in other namespaces, the error is corrected if the `DevBox` package is mapped in `%All`

**Comment by SeanConnelly** [comment]
%SYS, I bet im not escaping the %

Hey, thanks for finding errors Sergey!

**Comment by SeanConnelly** [comment]
fixed, thanks again
