### ISSUE TITLE
Colorize Escape Sequence

### ISSUE THREAD

**Issue by SergeyMi37** [SeanConnelly/DevBox#8]
![image](https://github.com/SeanConnelly/DevBox/assets/18187317/bc961c7b-d722-44b8-86d2-a7c3b086d30f)

That would be nice:-)

**Comment by SergeyMi37** [comment]
Or clean it up so it's easy to read

**Comment by SeanConnelly** [comment]
fixed :)

**Comment by SeanConnelly** [comment]
I think I will support terminal escapes at some point, but for now just going to strip them out, hopefully won't strip out non terminal escapes

**Comment by SergeyMi37** [comment]
Thx
